[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "commitizen>=4.8.2",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.3",
    "ruff>=0.11.13",
]
