name: "Continuous Integration"
run-name: Running tests on "${{ github.ref }}" by "${{ github.actor }}"
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 12 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: cd qasports && uv sync
      - run: cd qasports && uv run ruff check .
