name: "Continuous Integration"
run-name: Running tests on "${{ github.ref }}" by "${{ github.actor }}"
on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
  schedule:
  - cron: "0 12 1 * *"

jobs:
  ruff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: cd qasports && uv sync
      - run: cd qasports && uv run ruff check .
